name: Code Style Check

on: [push]

jobs:
  formatting-check:
    name: Check format of C
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++ sources
      uses: Northeastern-Electric-Racing/clang-format-action@main
      with:
        clang-format-version: '17'
        format-filepath: "./Drivers/Embedded-Base/clang-format"
